# Generated by Django 3.0.7 on 2020-07-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='user',
            new_name='payer',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='company',
            new_name='receiver',
        ),
    ]
