# Generated by Django 2.2.3 on 2020-06-13 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200612_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_company',
            new_name='corperation',
        ),
    ]
