# Generated by Django 3.0.7 on 2020-06-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20200612_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
