# Generated by Django 3.0.7 on 2020-06-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20200616_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
