# Generated by Django 3.0.7 on 2020-06-30 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20200616_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='corperation',
            new_name='corporation',
        ),
    ]
