# Generated by Django 3.0.7 on 2020-06-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20200629_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default='18 honey', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='industry',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(default=123, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='postal_code',
            field=models.CharField(default='sas', max_length=30),
            preserve_default=False,
        ),
    ]
